/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the ExportID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportID{}

// ExportID struct for ExportID
type ExportID struct {
	Id string `json:"id"`
}

// NewExportID instantiates a new ExportID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportID(id string) *ExportID {
	this := ExportID{}
	this.Id = id
	return &this
}

// NewExportIDWithDefaults instantiates a new ExportID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportIDWithDefaults() *ExportID {
	this := ExportID{}
	return &this
}

// GetId returns the Id field value
func (o *ExportID) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExportID) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExportID) SetId(v string) {
	o.Id = v
}

func (o ExportID) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableExportID struct {
	value *ExportID
	isSet bool
}

func (v NullableExportID) Get() *ExportID {
	return v.value
}

func (v *NullableExportID) Set(val *ExportID) {
	v.value = val
	v.isSet = true
}

func (v NullableExportID) IsSet() bool {
	return v.isSet
}

func (v *NullableExportID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportID(val *ExportID) *NullableExportID {
	return &NullableExportID{value: val, isSet: true}
}

func (v NullableExportID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


