/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the IndexDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexDeleteRequest{}

// IndexDeleteRequest struct for IndexDeleteRequest
type IndexDeleteRequest struct {
	Collection string `json:"collection"`
	Fields []string `json:"fields"`
}

// NewIndexDeleteRequest instantiates a new IndexDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexDeleteRequest(collection string, fields []string) *IndexDeleteRequest {
	this := IndexDeleteRequest{}
	this.Collection = collection
	this.Fields = fields
	return &this
}

// NewIndexDeleteRequestWithDefaults instantiates a new IndexDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexDeleteRequestWithDefaults() *IndexDeleteRequest {
	this := IndexDeleteRequest{}
	return &this
}

// GetCollection returns the Collection field value
func (o *IndexDeleteRequest) GetCollection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Collection
}

// GetCollectionOk returns a tuple with the Collection field value
// and a boolean to check if the value has been set.
func (o *IndexDeleteRequest) GetCollectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Collection, true
}

// SetCollection sets field value
func (o *IndexDeleteRequest) SetCollection(v string) {
	o.Collection = v
}

// GetFields returns the Fields field value
func (o *IndexDeleteRequest) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *IndexDeleteRequest) GetFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *IndexDeleteRequest) SetFields(v []string) {
	o.Fields = v
}

func (o IndexDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["collection"] = o.Collection
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

type NullableIndexDeleteRequest struct {
	value *IndexDeleteRequest
	isSet bool
}

func (v NullableIndexDeleteRequest) Get() *IndexDeleteRequest {
	return v.value
}

func (v *NullableIndexDeleteRequest) Set(val *IndexDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexDeleteRequest(val *IndexDeleteRequest) *NullableIndexDeleteRequest {
	return &NullableIndexDeleteRequest{value: val, isSet: true}
}

func (v NullableIndexDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


