/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the PaginationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationRequest{}

// PaginationRequest struct for PaginationRequest
type PaginationRequest struct {
	Page int32 `json:"page"`
	PerPage int32 `json:"perPage"`
}

// NewPaginationRequest instantiates a new PaginationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationRequest(page int32, perPage int32) *PaginationRequest {
	this := PaginationRequest{}
	this.Page = page
	this.PerPage = perPage
	return &this
}

// NewPaginationRequestWithDefaults instantiates a new PaginationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationRequestWithDefaults() *PaginationRequest {
	this := PaginationRequest{}
	return &this
}

// GetPage returns the Page field value
func (o *PaginationRequest) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PaginationRequest) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PaginationRequest) SetPage(v int32) {
	o.Page = v
}

// GetPerPage returns the PerPage field value
func (o *PaginationRequest) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *PaginationRequest) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *PaginationRequest) SetPerPage(v int32) {
	o.PerPage = v
}

func (o PaginationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["perPage"] = o.PerPage
	return toSerialize, nil
}

type NullablePaginationRequest struct {
	value *PaginationRequest
	isSet bool
}

func (v NullablePaginationRequest) Get() *PaginationRequest {
	return v.value
}

func (v *NullablePaginationRequest) Set(val *PaginationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationRequest(val *PaginationRequest) *NullablePaginationRequest {
	return &NullablePaginationRequest{value: val, isSet: true}
}

func (v NullablePaginationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


