/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the QueryObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryObject{}

// QueryObject struct for QueryObject
type QueryObject struct {
	Field string `json:"field"`
	Operator Operator `json:"operator"`
	Value QueryObjectValue `json:"value"`
}

// NewQueryObject instantiates a new QueryObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryObject(field string, operator Operator, value QueryObjectValue) *QueryObject {
	this := QueryObject{}
	this.Field = field
	this.Operator = operator
	this.Value = value
	return &this
}

// NewQueryObjectWithDefaults instantiates a new QueryObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryObjectWithDefaults() *QueryObject {
	this := QueryObject{}
	var operator Operator = EQ
	this.Operator = operator
	return &this
}

// GetField returns the Field field value
func (o *QueryObject) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *QueryObject) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *QueryObject) SetField(v string) {
	o.Field = v
}

// GetOperator returns the Operator field value
func (o *QueryObject) GetOperator() Operator {
	if o == nil {
		var ret Operator
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *QueryObject) GetOperatorOk() (*Operator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *QueryObject) SetOperator(v Operator) {
	o.Operator = v
}

// GetValue returns the Value field value
func (o *QueryObject) GetValue() QueryObjectValue {
	if o == nil {
		var ret QueryObjectValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *QueryObject) GetValueOk() (*QueryObjectValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *QueryObject) SetValue(v QueryObjectValue) {
	o.Value = v
}

func (o QueryObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["operator"] = o.Operator
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableQueryObject struct {
	value *QueryObject
	isSet bool
}

func (v NullableQueryObject) Get() *QueryObject {
	return v.value
}

func (v *NullableQueryObject) Set(val *QueryObject) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryObject) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryObject(val *QueryObject) *NullableQueryObject {
	return &NullableQueryObject{value: val, isSet: true}
}

func (v NullableQueryObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


