/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
	"fmt"
)

// QueryObjectValue struct for QueryObjectValue
type QueryObjectValue struct {
	float32 *float32
	int32 *int32
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *QueryObjectValue) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into float32
	err = json.Unmarshal(data, &dst.float32);
	if err == nil {
		jsonfloat32, _ := json.Marshal(dst.float32)
		if string(jsonfloat32) == "{}" { // empty struct
			dst.float32 = nil
		} else {
			return nil // data stored in dst.float32, return on the first match
		}
	} else {
		dst.float32 = nil
	}

	// try to unmarshal JSON data into int32
	err = json.Unmarshal(data, &dst.int32);
	if err == nil {
		jsonint32, _ := json.Marshal(dst.int32)
		if string(jsonint32) == "{}" { // empty struct
			dst.int32 = nil
		} else {
			return nil // data stored in dst.int32, return on the first match
		}
	} else {
		dst.int32 = nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(QueryObjectValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *QueryObjectValue) MarshalJSON() ([]byte, error) {
	if src.float32 != nil {
		return json.Marshal(&src.float32)
	}

	if src.int32 != nil {
		return json.Marshal(&src.int32)
	}

	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableQueryObjectValue struct {
	value *QueryObjectValue
	isSet bool
}

func (v NullableQueryObjectValue) Get() *QueryObjectValue {
	return v.value
}

func (v *NullableQueryObjectValue) Set(val *QueryObjectValue) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryObjectValue) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryObjectValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryObjectValue(val *QueryObjectValue) *NullableQueryObjectValue {
	return &NullableQueryObjectValue{value: val, isSet: true}
}

func (v NullableQueryObjectValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryObjectValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


