/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the DocumentDiffRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentDiffRequest{}

// DocumentDiffRequest struct for DocumentDiffRequest
type DocumentDiffRequest struct {
	Page int32 `json:"page"`
	PerPage int32 `json:"perPage"`
	Desc *bool `json:"desc,omitempty"`
}

// NewDocumentDiffRequest instantiates a new DocumentDiffRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentDiffRequest(page int32, perPage int32) *DocumentDiffRequest {
	this := DocumentDiffRequest{}
	this.Page = page
	this.PerPage = perPage
	return &this
}

// NewDocumentDiffRequestWithDefaults instantiates a new DocumentDiffRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentDiffRequestWithDefaults() *DocumentDiffRequest {
	this := DocumentDiffRequest{}
	return &this
}

// GetPage returns the Page field value
func (o *DocumentDiffRequest) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *DocumentDiffRequest) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *DocumentDiffRequest) SetPage(v int32) {
	o.Page = v
}

// GetPerPage returns the PerPage field value
func (o *DocumentDiffRequest) GetPerPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value
// and a boolean to check if the value has been set.
func (o *DocumentDiffRequest) GetPerPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PerPage, true
}

// SetPerPage sets field value
func (o *DocumentDiffRequest) SetPerPage(v int32) {
	o.PerPage = v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *DocumentDiffRequest) GetDesc() bool {
	if o == nil || IsNil(o.Desc) {
		var ret bool
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentDiffRequest) GetDescOk() (*bool, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *DocumentDiffRequest) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given bool and assigns it to the Desc field.
func (o *DocumentDiffRequest) SetDesc(v bool) {
	o.Desc = &v
}

func (o DocumentDiffRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentDiffRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["perPage"] = o.PerPage
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	return toSerialize, nil
}

type NullableDocumentDiffRequest struct {
	value *DocumentDiffRequest
	isSet bool
}

func (v NullableDocumentDiffRequest) Get() *DocumentDiffRequest {
	return v.value
}

func (v *NullableDocumentDiffRequest) Set(val *DocumentDiffRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentDiffRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentDiffRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentDiffRequest(val *DocumentDiffRequest) *NullableDocumentDiffRequest {
	return &NullableDocumentDiffRequest{value: val, isSet: true}
}

func (v NullableDocumentDiffRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentDiffRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


