/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the DocumentUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentUpdateRequest{}

// DocumentUpdateRequest struct for DocumentUpdateRequest
type DocumentUpdateRequest struct {
	Document map[string]interface{} `json:"document"`
	Query Query `json:"query"`
}

// NewDocumentUpdateRequest instantiates a new DocumentUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentUpdateRequest(document map[string]interface{}, query Query) *DocumentUpdateRequest {
	this := DocumentUpdateRequest{}
	this.Document = document
	this.Query = query
	return &this
}

// NewDocumentUpdateRequestWithDefaults instantiates a new DocumentUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentUpdateRequestWithDefaults() *DocumentUpdateRequest {
	this := DocumentUpdateRequest{}
	return &this
}

// GetDocument returns the Document field value
func (o *DocumentUpdateRequest) GetDocument() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Document
}

// GetDocumentOk returns a tuple with the Document field value
// and a boolean to check if the value has been set.
func (o *DocumentUpdateRequest) GetDocumentOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Document, true
}

// SetDocument sets field value
func (o *DocumentUpdateRequest) SetDocument(v map[string]interface{}) {
	o.Document = v
}

// GetQuery returns the Query field value
func (o *DocumentUpdateRequest) GetQuery() Query {
	if o == nil {
		var ret Query
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *DocumentUpdateRequest) GetQueryOk() (*Query, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *DocumentUpdateRequest) SetQuery(v Query) {
	o.Query = v
}

func (o DocumentUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["document"] = o.Document
	toSerialize["query"] = o.Query
	return toSerialize, nil
}

type NullableDocumentUpdateRequest struct {
	value *DocumentUpdateRequest
	isSet bool
}

func (v NullableDocumentUpdateRequest) Get() *DocumentUpdateRequest {
	return v.value
}

func (v *NullableDocumentUpdateRequest) Set(val *DocumentUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentUpdateRequest(val *DocumentUpdateRequest) *NullableDocumentUpdateRequest {
	return &NullableDocumentUpdateRequest{value: val, isSet: true}
}

func (v NullableDocumentUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


