/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the DocumentInsertManyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentInsertManyRequest{}

// DocumentInsertManyRequest struct for DocumentInsertManyRequest
type DocumentInsertManyRequest struct {
	Documents []map[string]interface{} `json:"documents"`
}

// NewDocumentInsertManyRequest instantiates a new DocumentInsertManyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentInsertManyRequest(documents []map[string]interface{}) *DocumentInsertManyRequest {
	this := DocumentInsertManyRequest{}
	this.Documents = documents
	return &this
}

// NewDocumentInsertManyRequestWithDefaults instantiates a new DocumentInsertManyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentInsertManyRequestWithDefaults() *DocumentInsertManyRequest {
	this := DocumentInsertManyRequest{}
	return &this
}

// GetDocuments returns the Documents field value
func (o *DocumentInsertManyRequest) GetDocuments() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value
// and a boolean to check if the value has been set.
func (o *DocumentInsertManyRequest) GetDocumentsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Documents, true
}

// SetDocuments sets field value
func (o *DocumentInsertManyRequest) SetDocuments(v []map[string]interface{}) {
	o.Documents = v
}

func (o DocumentInsertManyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentInsertManyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["documents"] = o.Documents
	return toSerialize, nil
}

type NullableDocumentInsertManyRequest struct {
	value *DocumentInsertManyRequest
	isSet bool
}

func (v NullableDocumentInsertManyRequest) Get() *DocumentInsertManyRequest {
	return v.value
}

func (v *NullableDocumentInsertManyRequest) Set(val *DocumentInsertManyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentInsertManyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentInsertManyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentInsertManyRequest(val *DocumentInsertManyRequest) *NullableDocumentInsertManyRequest {
	return &NullableDocumentInsertManyRequest{value: val, isSet: true}
}

func (v NullableDocumentInsertManyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentInsertManyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


