/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the SchemaTxMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaTxMetadata{}

// SchemaTxMetadata TxMetadata contains metadata set to whole transaction
type SchemaTxMetadata struct {
	// Entry expiration information
	TruncatedTxID *string `json:"truncatedTxID,omitempty"`
}

// NewSchemaTxMetadata instantiates a new SchemaTxMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaTxMetadata() *SchemaTxMetadata {
	this := SchemaTxMetadata{}
	return &this
}

// NewSchemaTxMetadataWithDefaults instantiates a new SchemaTxMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaTxMetadataWithDefaults() *SchemaTxMetadata {
	this := SchemaTxMetadata{}
	return &this
}

// GetTruncatedTxID returns the TruncatedTxID field value if set, zero value otherwise.
func (o *SchemaTxMetadata) GetTruncatedTxID() string {
	if o == nil || IsNil(o.TruncatedTxID) {
		var ret string
		return ret
	}
	return *o.TruncatedTxID
}

// GetTruncatedTxIDOk returns a tuple with the TruncatedTxID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaTxMetadata) GetTruncatedTxIDOk() (*string, bool) {
	if o == nil || IsNil(o.TruncatedTxID) {
		return nil, false
	}
	return o.TruncatedTxID, true
}

// HasTruncatedTxID returns a boolean if a field has been set.
func (o *SchemaTxMetadata) HasTruncatedTxID() bool {
	if o != nil && !IsNil(o.TruncatedTxID) {
		return true
	}

	return false
}

// SetTruncatedTxID gets a reference to the given string and assigns it to the TruncatedTxID field.
func (o *SchemaTxMetadata) SetTruncatedTxID(v string) {
	o.TruncatedTxID = &v
}

func (o SchemaTxMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaTxMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TruncatedTxID) {
		toSerialize["truncatedTxID"] = o.TruncatedTxID
	}
	return toSerialize, nil
}

type NullableSchemaTxMetadata struct {
	value *SchemaTxMetadata
	isSet bool
}

func (v NullableSchemaTxMetadata) Get() *SchemaTxMetadata {
	return v.value
}

func (v *NullableSchemaTxMetadata) Set(val *SchemaTxMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaTxMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaTxMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaTxMetadata(val *SchemaTxMetadata) *NullableSchemaTxMetadata {
	return &NullableSchemaTxMetadata{value: val, isSet: true}
}

func (v NullableSchemaTxMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaTxMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


