/*
Immudb Cloud Service

Specification of API to interact with Immudb Cloud Service.

API version: 1.0.0
Contact: contact@codenotary.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storage

import (
	"encoding/json"
)

// checks if the DocumentCountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentCountRequest{}

// DocumentCountRequest struct for DocumentCountRequest
type DocumentCountRequest struct {
	Query *Query `json:"query,omitempty"`
}

// NewDocumentCountRequest instantiates a new DocumentCountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentCountRequest() *DocumentCountRequest {
	this := DocumentCountRequest{}
	return &this
}

// NewDocumentCountRequestWithDefaults instantiates a new DocumentCountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentCountRequestWithDefaults() *DocumentCountRequest {
	this := DocumentCountRequest{}
	return &this
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *DocumentCountRequest) GetQuery() Query {
	if o == nil || IsNil(o.Query) {
		var ret Query
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentCountRequest) GetQueryOk() (*Query, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *DocumentCountRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given Query and assigns it to the Query field.
func (o *DocumentCountRequest) SetQuery(v Query) {
	o.Query = &v
}

func (o DocumentCountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentCountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableDocumentCountRequest struct {
	value *DocumentCountRequest
	isSet bool
}

func (v NullableDocumentCountRequest) Get() *DocumentCountRequest {
	return v.value
}

func (v *NullableDocumentCountRequest) Set(val *DocumentCountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentCountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentCountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentCountRequest(val *DocumentCountRequest) *NullableDocumentCountRequest {
	return &NullableDocumentCountRequest{value: val, isSet: true}
}

func (v NullableDocumentCountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentCountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


