/*
Immudb Cloud Service

Testing ExportAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package storage

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/WladOd/auction.git/storage"
)

func Test_storage_ExportAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ExportAPIService GetExportInformation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ledger string

		resp, httpRes, err := apiClient.ExportAPI.GetExportInformation(context.Background(), ledger).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExportAPIService S3Export", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ledger string

		resp, httpRes, err := apiClient.ExportAPI.S3Export(context.Background(), ledger).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
