/*
Immudb Cloud Service

Testing IndexesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package storage

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/WladOd/auction.git/storage"
)

func Test_storage_IndexesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IndexesAPIService CreateIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ledger string
		var collection string

		resp, httpRes, err := apiClient.IndexesAPI.CreateIndex(context.Background(), ledger, collection).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IndexesAPIService DeleteIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ledger string
		var collection string

		resp, httpRes, err := apiClient.IndexesAPI.DeleteIndex(context.Background(), ledger, collection).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
